feat(google): create brownbaglast command
Codeminer42/marvin-cm42 pull request #32
Opened 2021-12-02 16:16 UTC by matheushahnn

- [x] Tests for the changes have been added (for bug fixes / features)

This PR creates a new command to print the last upcoming stream video schedule following the message design from !brownbagnext command

![image](https://user-images.githubusercontent.com/7703431/144459536-1f225698-642f-45d1-8d41-9ba87a5e4b2a.png)

Feasture request https://github.com/Codeminer42/marvin-cm42/issues/31

2021-12-03 14:06 UTC, matheushahnn commented on lib/google/youtube.js
> +    await getLastStream({ max, status, pageToken: streams?.nextPageToken })
There is no order param in liveBroadcasts.list API https://developers.google.com/youtube/v3/live/docs/liveBroadcasts/list
if we add a param order: 'date' it will append in the GET though. The order is crescent and I couldn't find a way to get the last stream video on top of the results. That is why I followed the nextPageToken approach.

2022-05-27 19:43 UTC, paulodiovani requested changes
getting an error while trying to run:

```
marvin> !brownbaglast
marvin> Hey, I haven't found anything, but you can add using: `marvin add command <key> "val"`
streams.items?.at is not a function
```

2022-05-27 19:43 UTC, paulodiovani commented on lib/google/youtube.js
> +    await getLastStream({ max, status, pageToken: streams?.nextPageToken })
the returning of this call if never used, so you will never really get the last scheduled stream, but only the first page.
you probably want:

```suggestion
    const nextPageStreams = await getLastStream({ max, status, pageToken: streams?.nextPageToken })
    return nextPageStreams.items?.at(-1) || null
```

Notes to consider:

- make sure you get results from `nextPageStreams` or do not return from the block
- use a smaller limit (e.g. `max: 1`) when testing to get more pages

2022-05-27 19:43 UTC, paulodiovani commented on lib/google/youtube.js
> +  return streams.items?.at(-1) || null
I'm getting an error on my local env:

> streams.items?.at is not a function

This is not expected as there are existing scheduled streams, so I should get a response.

2022-05-27 19:43 UTC, paulodiovani commented on lib/utils.js
> +}
I don't see a reason to move this code here.

If you want to separate the returned messages from the `scripts/*` folder, please create `lib/messages.js` or similar for that. DO NOT use `utils/` for everything.

2022-05-27 19:43 UTC, paulodiovani commented on scripts/google.js
> +//   !brownbaglast - the last schedule video
Note, every new defined command must be included in https://github.com/matheushahnn/marvin-cm42/blob/514c90bdf51600f2df045a4e04cc97febcd57472/scripts/customCommand.js#L7-L23 to prevent the bot trying to find a custom one:

> Hey, I haven't found anything, but you can add using: `marvin add command <key> "val"`

2022-05-27 19:43 UTC, paulodiovani commented on scripts/google.js
> +      .then((streams) => streams.map(brownBagMessageList))
is this really the correct place, as the code that `brownBagMessageList` replaces was at line 170 :thinking:

2022-05-31 20:18 UTC, matheushahnn commented on scripts/google.js
> +//   !brownbaglast - the last schedule video
Created, thank you for the help 👍

2022-05-31 20:20 UTC, matheushahnn commented on lib/google/youtube.js
> +    await getLastStream({ max, status, pageToken: streams?.nextPageToken })
I changed this part, please lmk if it is correct now. 
Changed the max to 1 and it is returning the last brownbag scheduled. Just it took more time with max = 1.

2022-05-31 20:20 UTC, matheushahnn commented on lib/utils.js
> +}
I removed this shared message.

2022-05-31 20:21 UTC, matheushahnn commented on scripts/google.js
> +      .then((streams) => streams.map(brownBagMessageList))
I removed the `brownBagMessageList`

2022-06-06 14:17 UTC, ramos-ph submitted a review, later dismissed
LGTM.

![image](https://user-images.githubusercontent.com/50644753/174317287-e8937c0a-fc3b-4671-adfb-347a16f090a0.png)

2022-06-29 12:57 UTC, paulodiovani commented on scripts/google.js
> +            : null
Considering the intend for this use, I think we can change this text a bit.
Here is a suggestion:

```suggestion
          `A última brownbag agendada será em _${dateStr}_,`,
          'Novos envios serão apresentados após esta data.',
          '',
          'Use o comando `!brownbag` para obter informações de como enviar a sua.',
```

The original idea for this command is to get an idea of how long will take for new submissions to be presented, so we don't really need the information on which stream will it be.

2022-06-29 12:59 UTC, paulodiovani commented on test/scripts/google_test.js
> +  describe('!brownbaglast', () => {
use blank lines to separate code blocks

```suggestion

  describe('!brownbaglast', () => {
```

2022-07-01 18:04 UTC, matheushahnn commented on lib/google/youtube.js
> +    const nextPageStreams = await getLastStream({ max, status, pageToken: streams?.nextPageToken })
You are right, I removed the optional chaining.

2022-07-01 18:04 UTC, matheushahnn commented on scripts/google.js
> +            : null
Ok, I updated the message.

2022-07-05 15:43 UTC, paulodiovani requested changes

2022-07-05 15:43 UTC, paulodiovani commented on lib/google/youtube.js
> +  const streams = await getStreamsData({ max, status, pageToken })
you misunderstood,
I suggest to set `max = 1` just for testing, we should NOT force the script to make so many requests.

Set it to `100` (or whatever is the max allowed from youtube) for the final version

2022-07-05 15:43 UTC, paulodiovani commented on lib/google/youtube.js
> +  const streams = await getStreamsData({ max, status, pageToken })
The `getLastStream` does not need to accept the neither `max` nor the `status` arguments, as its name suggest it will always reach until the last one,

```suggestion
const MAX_STREAMS = 100; //check the best limit to be used and move this to before function definitions

const getLastStream = async ({ pageToken = '' } = {}) => {
  const streams = await getStreamsData({ max: MAX_STREAMS, status: 'upcoming', pageToken })
```

2022-07-05 19:45 UTC, matheushahnn commented on lib/google/youtube.js
> +    return streams.items || []
Got it! It makes sense.

2022-07-05 19:45 UTC, matheushahnn commented on lib/google/youtube.js
> +  const streams = await getStreamsData({ max, status, pageToken })
Done!

2022-07-20 18:21 UTC, paulodiovani approved these changes

2022-07-20 18:21 UTC, merged